{% set name = "tabulate" %}
{% set version = "0.8.7" %}
{% set sha256 = "db2723a20d04bcda8522165c73eea7c300eda74e0ce852d9022e0159d7895007" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - tabulate = tabulate:_main

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - tabulate

  commands:
    - tabulate --help

about:
  home: https://bitbucket.org/astanin/python-tabulate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pretty-print tabular data in Python, a library and a command-line utility.'
  dev_url: https://bitbucket.org/astanin/python-tabulate

extra:
  recipe-maintainers:
    - jakirkham
    - synapticarbors
