{% set name = "tabulate" %}
{% set version = "0.10.0" %}
{% set sha256 = "e2cfde8f79420f6deeffdeda9aaec3b6bc5abce947655d17ac662b126e48a60d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - tabulate = tabulate:_main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python

test:
  imports:
    - tabulate
  requires:
    - pip
  commands:
    - pip check
    - tabulate --help

about:
  home: https://github.com/astanin/python-tabulate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pretty-print tabular data in Python, a library and a command-line utility.
  description: Pretty-print tabular data in Python, a library and a command-line utility.
  dev_url: https://github.com/astanin/python-tabulate
  doc_url: https://github.com/astanin/python-tabulate/blob/master/README.md

extra:
  recipe-maintainers:
    - jakirkham
    - synapticarbors
