{% set name = "tabulate" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2cfde8f79420f6deeffdeda9aaec3b6bc5abce947655d17ac662b126e48a60d

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - tabulate = tabulate:_main

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - setuptools_scm >=3.4.3
  run:
    - python

test:
  source_files:
    - test
    # OSError: b"$PREFIX/bin/python: can't open file '$SRC_DIR/tabulate/__init__.py': [Errno 2] No such file or directory\n"
    - tabulate/__init__.py
  imports:
    - tabulate
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest test
    - tabulate --help

about:
  home: https://github.com/astanin/python-tabulate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pretty-print tabular data in Python, a library and a command-line utility.
  description: Pretty-print tabular data in Python, a library and a command-line utility.
  dev_url: https://github.com/astanin/python-tabulate
  doc_url: https://github.com/astanin/python-tabulate/blob/master/README.md

extra:
  recipe-maintainers:
    - jakirkham
    - synapticarbors
