travis:
  secure:
    BINSTAR_TOKEN: cSeCPwhUtC2x9vJ/ornH72uVqF2G3zaZ80MH1PEQWW8pYvvdeTfRNv4WsEOJAC4vP0aJngESUXt1lQgpEVPQTfVuSXpVmSLnjIyQaDcGNKT2/KpnH5Tiq/ps4Et5x+pcPjtOWw0mvPDKpSlgBufX3S1DzBb2XFKTpvES2oB+2KkFNhdm3N45J8dSnwDVO8FaxpiDk2iYfDOVOKmYP6bli0HMVCCzsB8eMlcrl1vxg3StwbZtVje+q9ypqj83vcNaS6w9t1/6micfjx0MmOAY/z5BDerT6xVbXD9QbP2R6wPNtwvVGFzqVyytVSmRbTrh0ApkGydMYGTbWQMHokYXB9Nm6prATooe1Z8R+bcG3FOXnfgP3bwT/WzA36bYVIeow/T4qAn2X9UpDDuryRnBbHrVUfDpRz3+3GYhWwzgfcuvY7c7D4QJUcWkADtY5w2TjqVgijLDBolNIj3s4vC/m37/LwS7NmwLGux/chkIeKLrTHZsMnhrNqtVM2Ijhn5dTtDat5xAdaZSvQ1lOf3P1lqR+E+z8ge5/bjRHIJhp6woEGNkU9D+wChhMJTZ4jy6SDd3xRByvW2iprgL3gXs0I3b6Dj4+usVJ/PCX7edqHBAE4ypr9n6ZpWfmo/pgHamGJP+x/7mFZYLse77qC7Pv1Xiz4J7dMn4Fig4+qsreSI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
